# Generated by Django 5.2.7 on 2025-10-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('ingestion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_text', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperiq_ai.document')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(max_length=100)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperiq_ai.document')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='paperiq_ai.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='paperiq_ai.entity')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_text', models.CharField(max_length=255)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperiq_ai.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperiq_ai.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperiq_ai.user')),
            ],
        ),
    ]
